# Generated by Django 6.0.1 on 2026-01-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('asset_class', models.CharField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('reit', 'REIT'), ('commodity', 'Comodity'), ('cash', 'Cash')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
            ],
        ),
    ]
