# Generated by Django 6.0.1 on 2026-01-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_price_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('ticker', models.CharField(max_length=10, verbose_name='Ticker')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平均買値（ドル）')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='現在価格（ドル）')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=150.0, max_digits=6, verbose_name='為替レート')),
            ],
        ),
    ]
