# Generated by Django 6.0.1 on 2026-01-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_holding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='holding',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名前'),
        ),
    ]
