# Generated by Django 6.0.1 on 2026-02-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_delete_asset_delete_price_delete_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='current_price_jpy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='現在価格（円）'),
        ),
    ]
