# Generated by Django 6.0.1 on 2026-02-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_holding_current_price_jpy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holding',
            new_name='Asset',
        ),
    ]
