# Generated by Django 6.0.1 on 2026-02-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_holding_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(choices=[('JP_STOCK', '日本株'), ('US_STOCK', '海外株'), ('REAL_ESTATE', '不動産'), ('GOLD', '貴金属'), ('JP_BOND', '国内債券'), ('US_BOND', '海外債権'), ('CASH', '現金')], default='JP_STOCK', max_length=20),
        ),
    ]
