# Generated by Django 6.0.1 on 2026-02-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_asset_asset_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='average_price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='current_price',
        ),
        migrations.AddField(
            model_name='asset',
            name='average_price_jpy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='平均買値（JPY）'),
        ),
        migrations.AddField(
            model_name='asset',
            name='average_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='平均買値（USD）'),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='現在価格（USD）'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(choices=[('JP_STOCK', '日本株'), ('US_STOCK', '海外株'), ('JP_FUND', '投資信託'), ('JP_BOND', '国内債券'), ('US_BOND', '海外債権'), ('CASH', '現金')], default='JP_FUND', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_price_jpy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='現在価格（JPY）'),
        ),
    ]
