# Generated by Django 6.0.1 on 2026-02-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_asset_average_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(choices=[('US_STOCK', '外国株'), ('US_BND', '外国債権'), ('US_MMF', 'ドル建てMMF'), ('US_CASH', 'ドル建て現金'), ('JP_STOCK', '日本株'), ('JP_FUND', '投資信託'), ('JP_BND', '国内債券'), ('JP_CASH', '現金')], default='JP_FUND', max_length=20),
        ),
    ]
