# Generated by Django 6.0.1 on 2026-02-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_asset_asset_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量'),
        ),
    ]
