# Generated by Django 6.0.1 on 2026-02-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_asset_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='account_type',
            field=models.CharField(blank=True, choices=[('TAXABLE', '特定'), ('NISA', 'NISA')], max_length=20, null=True, verbose_name='口座種別'),
        ),
        migrations.AddField(
            model_name='asset',
            name='financial_institution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='金融機関名'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所有者'),
        ),
    ]
