# Generated by Django 6.0.1 on 2026-03-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_asset_account_type_asset_financial_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
    ]
