# Generated by Django 6.0.1 on 2026-03-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ticker'),
        ),
    ]
