# Generated by Django 6.0.1 on 2026-03-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_asset_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='average_exchange_rate',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=6, verbose_name='取得時平均為替レート'),
        ),
    ]
